services:
  - type: web
    name: flux-electro-mechanical
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: COOKIE_SECURE
        value: "true"
      - key: DATABASE_URL
        sync: false
